# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Theodore Jagodits
title: Grad Student
email: tjagodit (at uci dot edu)
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  tbjag
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: teddyjagodits
linkedin_username: theodore-jagodits-140772144
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Hi, my name is Theo, and I am originally from Montgomery County, Maryland. Currently, I am getting my M.S. of Computer Science at [UC Irvine](https://uci.edu/).
  Some of my interests include software engineering, machine learning, distributed systems and architectures.
  As a person, I try to challenge myself every day. I like challenging myself in my work and outside of work looking for new experiences.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: PFAS Lab
        link: https://olivareslab.org/research-team/
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          - Using deep learning techniques to predict a common class of pollutants called ‘forever’ chemicals in the environmental
            engineering lab under the direction of Professor Olivares. The project aimed to develop predictive models that could identify
            contamination patterns in a spatial context and predict the location of places of extreme environmental hazard. In order to
            assess the environmental impact of these persistent pollutants, contributing to ongoing efforts in pollution mitigation.
          - Preprocessed GIS data from various sources into machine learning datasets, selected machine learning models and worked on
            statistical analysis of data to select appropriate features.

      - layout: left
        border: weak
        title: BIAS Lab
        link: https://biaslab.ics.uci.edu/
        description: | 
          Hyperdimensional computing project. TBD

      - layout: left
        border: weak
        title: CTM Insights Database Integrity
        link: https://biaslab.ics.uci.edu/
        quote: >
          Capstone Project
        description: | 
          - Designed a system for a JDBC driver to protect the integrity of databases using overlapping hashes for live data.
          - Held standup meetings with our team; Facilitated discussions with our sponsor and advisor. Filled out biweekly reports for
            the class itself and set milestones for our team. Wrote use cases for various database queries a user is expected to make.
          - Developed a C++ and Spring Boot micro services to demo our product to the sponsor of a live version of the system.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: General Atomics
        sub_title: Algorithms Graduate Intern
        caption: June 2024 - August 2024
        link: https://www.ga.com/
        description: | # this will include new lines to allow paragraphs
          - Developed data generation framework for the use case of simulating signals on different antenna array configurations.
          - Created convolutional neural network models with PyTorch on simulated data, to estimate the direction of arrival of signals coming into an antenna array. Showing a two percent accuracy increase opposed to traditional methods. 

      - layout: left
        title: The MITRE Corporation
        sub_title: Software Developer II
        caption: June 2021 - August 2023
        link: https://www.mitre.org/
        description: | # this will include new lines to allow paragraphs
          - Created data aggregation systems within a microservices architecture using Spring Boot ingesting from Kafka events. Ensured reliability by doing test-driven development. Deployed services to AWS using Gitlab CI/CD ensuring scalability.
          - Worked as a sub-reviewer for the Join Digital Library Conference under the direction of Dr. Justin Brunelle; read and
            reviewed a research paper for technical foundations and also if it was a good fit for the JDLC
          - Designed database filtering solution for the Kessel Run project using PostgresQL and MySQL on Spring Boot applications. This solution allows access to US allies onto sensitive applications by only exposing information relevant to the user. 
          - Mentored seven interns and acted as subject matter expert for their summer project for microservice architecture and security.

      - layout: left
        title: Air Force Civil Service
        sub_title: College Intern
        caption: May 2020 - August 2020
        link: https://afciviliancareers.com/
        description: | # this will include new lines to allow paragraphs
          - Led and actively participated in several collaborative student projects, specifically designed to test and enhance project management skills, including planning, task delegation, time management, and effective communication.
          - Co-authored an exploratory paper on Apache Spark to apply large-scale data analysis and processing in the Air Force.

      - layout: left
        title: Leidos Inc.
        sub_title: College Intern
        caption: June 2017 - August 2018
        link: https://www.leidos.com/
        description: | # this will include new lines to allow paragraphs
          - Programmed a categorizer in Excel to organize software licenses based on its requirements (i.e. GNU, MIT, etc.)
          - Created unit tests for flight control towers to digitize analog systems for health and longevity of flight controllers

  - title: Education
    layout: list
    content:
      - title: University of California, Irvine; Donald Bren School of Information & Computer Sciences
        sub_title: M.S. Computer Science
        caption: 2023 - Present
        description: | 
          Currently attending UCI for computer science to get more technical knowledge in fields that interest me. 

          I have founded the F1Tenth Autonomous Racing club that consists of writing machine learning models for small cars to compete against at top robotics conferences. 
      - title: Stevens Institute of Technology; Schaefer School of Engineering & Science
        sub_title: B.S. Computer Science
        caption: 2017 - 2021
        description: | 
          During my degree at Stevens I learnt lots of key skills such as team work and project management. During my last year, 
          a few classmates and I worked on a capstone project involving database security that ended up winning best project for the computer science department. 

          During my time there I was a participating member of the Varsity swim team which won many end of year conference championships during my time there.
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Full Stack Development:** React, Node.js, OAuth2, Spring Boot, GraphQL, PostgresQL, MongoDB, Redis, Linux, Scripting

      **Cloud Experience:** AWS, Docker, Kubernetes, Reverse-Proxies, System Design, ETL, Git, REST, Apache Spark, Kafka

      **Development Practices:** CI/CD, Unit Testing, Integration Testing, Test-Driven Development, Performance Optimization

      **Machine Learning & Data Science:** Pandas, Seaborn, Jupyter, Sklearn, Pytorch, Deep Learning, Statistical Analysis

      **Software Languages:** Java, Python, Javascript, Typescript, Go, C, C++, Erlang, SQL, HTML, CSS, learning Rust

      **Languages:** English (Fluent), Dutch (Fluent), German (Fluent), Portuguese (Basic), Spanish (Basic)

      **Errata:** Founder and President of F1Tenth Autonomous Racing @UCI; Avid Swimmer, Runner, Triathlete, Surfer, Skier, Climber; 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
